app:
  serviceName: "golang-jwt-auth"
  host: "0.0.0.0"
  port: 8083
rateLimit:
  rateLimitEnabled: true
  rateLimitCount: 10
  rateLimitPeriodInMinutes: 1
  rateLimitCleanupIntervalInSeconds: 180
  rateLimitWaitPeriodInSeconds: 180